@baseUrl = http://localhost:3001/api/auth

###
POST {{baseUrl}}/signup
Content-Type: application/json

{
  "name": "Test User",
  "email": "test@example.com",
  "password": "password123"
}

###
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123"
}
